image: docker.porscheinformatik.com/eenv/builders/default:jdk-17

stages:
  - build
  - deploy
  - acceptence-tests
  - deploy-idle
  - cleanup

build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  stage: build
  interruptible: true
  variables:
    MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -Djib.from.auth.username=$DOCKER_REGISTRY_USER -Djib.from.auth.password=$DOCKER_REGISTRY_PASSWORD -Djib.to.auth.username=$DOCKER_REGISTRY_USER -Djib.to.auth.password=$DOCKER_REGISTRY_PASSWORD'
  script:
    - npm ci
    - mvn $MAVEN_CLI_OPTS compile
    - npm run build
    - mvn $MAVEN_CLI_OPTS package jib:build -DfromImage=docker.porscheinformatik.com/eenv/service-java:17 -Dentrypoint=INHERIT -Djib.container.creationTime=`git show -s --format=%cI $CI_COMMIT_SHA` -DimageTag=$CI_COMMIT_REF_SLUG

build-sonarqube:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  stage: build
  interruptible: true
  script:
    - npm ci
    - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
    - mvn -B sonar:sonar

build-sonarqube-qa:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  stage: build
  interruptible: true
  allow_failure: true
  script:
    - npm ci
    - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
    - SONAR_HOST_URL=$SONAR_QA_HOST_URL SONAR_TOKEN=$SONAR_QA_TOKEN mvn -B sonar:sonar

.deploy:
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN"
    - oc project $OPENSHIFT_PROJECT
    - |
      function deploy_name() {
        if [[ "$CI_COMMIT_REF_SLUG" == "main" ]]; then
          name='prod'
        else
          name="mr-$CI_MERGE_REQUEST_ID"
        fi
        name=${name:0:45}
        name=${name%-}
        echo "ash-$name"
      }
  script:
    - helm repo add porscheinformatik ${HELM_REPO_URL} --username ${HELM_REPO_USER} --password ${HELM_REPO_PASSWORD}
    - helm upgrade --install --atomic --history-max 5 --namespace ${OPENSHIFT_PROJECT} $(deploy_name) -f deploy/${HELM_VALUES} --set appVersion="v`date +'%Y%m%d-%H%M%S'`" --set image.tag=$CI_COMMIT_REF_SLUG --set route.host=$APP_HOST --set postgresql.postgresPassword="${POSTGRESQL_PASSWORD}" porscheinformatik/web-application

deploy-review:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  extends: .deploy
  stage: deploy
  variables:
    APP_HOST: ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
    HELM_VALUES: 'values-review.yaml'
  environment:
    name: review/mr-$CI_MERGE_REQUEST_ID
    url: https://ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
    on_stop: stop-review

acceptence-tests:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  image: docker.io/cypress/base:18.12.1
  stage: acceptence-tests
  interruptible: true
  variables:
    CYPRESS_baseUrl: https://ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
  before_script:
    - cd heroes-acceptence-tests
    - npm i
  script:
    - npm test
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - heroes-acceptence-tests/cypress/videos

deploy-production:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
  extends: .deploy
  stage: deploy
  variables:
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
    HELM_VALUES: 'values-prod.yaml'
  environment:
    name: production
    url: https://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN

deploy-review-idle:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  extends: .deploy
  stage: deploy-idle
  script:
    - webapp_name="$(deploy_name)-web-application"
    - oc idle "${webapp_name:0:63}"

stop-review:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
  extends: .deploy
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - helm3 --namespace ${OPENSHIFT_PROJECT} delete $(deploy_name)
  environment:
    name: review/mr-$CI_MERGE_REQUEST_ID
    action: stop
